source 'https://rubygems.org'

ruby '2.7.2'
gem 'rails', '5.2.4.5'
gem 'sass-rails', '5.1.0'
gem 'uglifier', '1.3.0'
gem 'coffee-rails', '5.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'omniauth', '1.9.1'
gem 'omniauth-google-oauth2', '0.7.0'
gem 'devise'
gem 'thin'
gem 'figaro'
gem 'draper'
gem 'react-rails', '~>1.10.0'
gem 'redcarpet'
gem 'pg', '~> 0.21.0'
gem 'acts_as_commentable_with_threading'
gem 'rails_12factor'
gem 'ruby_native_statistics'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'better_errors'
end
